[package]
name = "chili"
version = "0.1.0"
edition = "2021"

[features]
bench = ["dep:divan", "dep:rayon"]

[dependencies]
divan = { version = "0.1.14", optional = true }
rayon = { version = "1.10.0", optional = true }

[[bench]]
name = "overhead"
harness = false
required-features = ["bench"]
